### ISSUE TITLE
Change of language

### ISSUE THREAD

**Issue by peterkilcoyne** [RonenR/Audactive#8]
when changing language within a resource. e.g. there is a paragraph of text in French and then I ask a question where English is selected, the question is read in English but with a French voice. The answers are then read with an English voice. How do I get the question read in English voice?

**Comment by RonenR** [comment]
Morning Peter!

The question is read - just like any paragraph - by the reading language set to that paragraph. 
The reading language set to a paragraph is defined by the most recent 'Language Switcher' block - or - if none - by the document's reading language.

Switching the 'input language' in a question block only affects the ANSWERS - cause they are the expected input. It does not affect the question.

So - if you like the question to be read in a different language - you should prepend it with a respective language switcher block.

Cheers,

Ronen
